<<<<<<< HEAD
name = "chat"
main = "src/worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "CHAT_KV", id = "3f48e77d245f41bfa2fbc1852bf7c98b" }
]

[vars]
ROOM_ID = "default-room"
MAX_MESSAGES = "500"
API_KEY = ""
APP_VERSION_CODE = "1"
APP_VERSION_NAME = "1.1.4"
APP_DOWNLOAD_URL = "https://chat.zztxer.dpdns.org/app-debug.apk"
APP_CHANGELOG = ""
APP_FORCE_UPDATE = "false"
APP_MIN_SDK = "24"
=======
name = "chat"
main = "src/worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "CHAT_KV", id = "3f48e77d245f41bfa2fbc1852bf7c98b" }
]

[vars]
ROOM_ID = "default-room"
MAX_MESSAGES = "500"
API_KEY = ""
APP_VERSION_CODE = "1"
APP_VERSION_NAME = "1.1.4"
APP_DOWNLOAD_URL = "https://chat.zztxer.dpdns.org/app-debug.apk"
APP_CHANGELOG = ""
APP_FORCE_UPDATE = "false"
APP_MIN_SDK = "24"
>>>>>>> 32a88550df533920ad83140f53de09a8489b391c
